/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdviserDashboardRouteImport } from './routes/adviser-dashboard'
import { Route as BecomeAnAdviserRouteImport } from './routes/become-an-adviser'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdvisersIndexRouteImport } from './routes/advisers.index'
import { Route as AdvisersAdviserIdRouteImport } from './routes/advisers.$adviserId'
import { Route as AdvisorDashboardRouteImport } from './routes/advisor.dashboard'
import { Route as AdvisorOnboardingRouteImport } from './routes/advisor.onboarding'
import { Route as BookAdviserIdRouteImport } from './routes/book.$adviserId'
import { Route as OnboardingSelectRoleRouteImport } from './routes/onboarding.select-role'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentOnboardingRouteImport } from './routes/student.onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviserDashboardRoute = AdviserDashboardRouteImport.update({
  id: '/adviser-dashboard',
  path: '/adviser-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnAdviserRoute = BecomeAnAdviserRouteImport.update({
  id: '/become-an-adviser',
  path: '/become-an-adviser',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisersIndexRoute = AdvisersIndexRouteImport.update({
  id: '/advisers/',
  path: '/advisers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisersAdviserIdRoute = AdvisersAdviserIdRouteImport.update({
  id: '/advisers/$adviserId',
  path: '/advisers/$adviserId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorDashboardRoute = AdvisorDashboardRouteImport.update({
  id: '/advisor/dashboard',
  path: '/advisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorOnboardingRoute = AdvisorOnboardingRouteImport.update({
  id: '/advisor/onboarding',
  path: '/advisor/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAdviserIdRoute = BookAdviserIdRouteImport.update({
  id: '/book/$adviserId',
  path: '/book/$adviserId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSelectRoleRoute = OnboardingSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => OnboardingRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOnboardingRoute = StudentOnboardingRouteImport.update({
  id: '/student/onboarding',
  path: '/student/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adviser-dashboard': typeof AdviserDashboardRoute
  '/become-an-adviser': typeof BecomeAnAdviserRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advisers/$adviserId': typeof AdvisersAdviserIdRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/onboarding': typeof AdvisorOnboardingRoute
  '/book/$adviserId': typeof BookAdviserIdRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/advisers/': typeof AdvisersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adviser-dashboard': typeof AdviserDashboardRoute
  '/become-an-adviser': typeof BecomeAnAdviserRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advisers/$adviserId': typeof AdvisersAdviserIdRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/onboarding': typeof AdvisorOnboardingRoute
  '/book/$adviserId': typeof BookAdviserIdRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/advisers': typeof AdvisersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adviser-dashboard': typeof AdviserDashboardRoute
  '/become-an-adviser': typeof BecomeAnAdviserRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advisers/$adviserId': typeof AdvisersAdviserIdRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/onboarding': typeof AdvisorOnboardingRoute
  '/book/$adviserId': typeof BookAdviserIdRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/advisers/': typeof AdvisersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adviser-dashboard'
    | '/become-an-adviser'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/verify-email'
    | '/advisers/$adviserId'
    | '/advisor/dashboard'
    | '/advisor/onboarding'
    | '/book/$adviserId'
    | '/onboarding/select-role'
    | '/student/dashboard'
    | '/student/onboarding'
    | '/advisers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adviser-dashboard'
    | '/become-an-adviser'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/verify-email'
    | '/advisers/$adviserId'
    | '/advisor/dashboard'
    | '/advisor/onboarding'
    | '/book/$adviserId'
    | '/onboarding/select-role'
    | '/student/dashboard'
    | '/student/onboarding'
    | '/advisers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adviser-dashboard'
    | '/become-an-adviser'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/verify-email'
    | '/advisers/$adviserId'
    | '/advisor/dashboard'
    | '/advisor/onboarding'
    | '/book/$adviserId'
    | '/onboarding/select-role'
    | '/student/dashboard'
    | '/student/onboarding'
    | '/advisers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdviserDashboardRoute: typeof AdviserDashboardRoute
  BecomeAnAdviserRoute: typeof BecomeAnAdviserRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdvisersAdviserIdRoute: typeof AdvisersAdviserIdRoute
  AdvisorDashboardRoute: typeof AdvisorDashboardRoute
  AdvisorOnboardingRoute: typeof AdvisorOnboardingRoute
  BookAdviserIdRoute: typeof BookAdviserIdRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentOnboardingRoute: typeof StudentOnboardingRoute
  AdvisersIndexRoute: typeof AdvisersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adviser-dashboard': {
      id: '/adviser-dashboard'
      path: '/adviser-dashboard'
      fullPath: '/adviser-dashboard'
      preLoaderRoute: typeof AdviserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-adviser': {
      id: '/become-an-adviser'
      path: '/become-an-adviser'
      fullPath: '/become-an-adviser'
      preLoaderRoute: typeof BecomeAnAdviserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisers/': {
      id: '/advisers/'
      path: '/advisers'
      fullPath: '/advisers/'
      preLoaderRoute: typeof AdvisersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisers/$adviserId': {
      id: '/advisers/$adviserId'
      path: '/advisers/$adviserId'
      fullPath: '/advisers/$adviserId'
      preLoaderRoute: typeof AdvisersAdviserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/dashboard': {
      id: '/advisor/dashboard'
      path: '/advisor/dashboard'
      fullPath: '/advisor/dashboard'
      preLoaderRoute: typeof AdvisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/onboarding': {
      id: '/advisor/onboarding'
      path: '/advisor/onboarding'
      fullPath: '/advisor/onboarding'
      preLoaderRoute: typeof AdvisorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$adviserId': {
      id: '/book/$adviserId'
      path: '/book/$adviserId'
      fullPath: '/book/$adviserId'
      preLoaderRoute: typeof BookAdviserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/select-role': {
      id: '/onboarding/select-role'
      path: '/select-role'
      fullPath: '/onboarding/select-role'
      preLoaderRoute: typeof OnboardingSelectRoleRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/onboarding': {
      id: '/student/onboarding'
      path: '/student/onboarding'
      fullPath: '/student/onboarding'
      preLoaderRoute: typeof StudentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingSelectRoleRoute: typeof OnboardingSelectRoleRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingSelectRoleRoute: OnboardingSelectRoleRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdviserDashboardRoute: AdviserDashboardRoute,
  BecomeAnAdviserRoute: BecomeAnAdviserRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdvisersAdviserIdRoute: AdvisersAdviserIdRoute,
  AdvisorDashboardRoute: AdvisorDashboardRoute,
  AdvisorOnboardingRoute: AdvisorOnboardingRoute,
  BookAdviserIdRoute: BookAdviserIdRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentOnboardingRoute: StudentOnboardingRoute,
  AdvisersIndexRoute: AdvisersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
